/**
 * Assembles all batch JSON files into a single dailyReflections.ts with 365 entries.
 * Usage: node scripts/assemble-365.js
 */
const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const batches = [];
const batchNames = [];
for (let i = 1; i <= 11; i++) batchNames.push(`batch${i}`);
batchNames.push('batch12-fill');

for (const name of batchNames) {
  const file = path.join(dataDir, `${name}.json`);
  if (fs.existsSync(file)) {
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    batches.push(...data);
    console.log(`${name}: ${data.length} entries`);
  }
}
console.log(`Total loaded: ${batches.length}`);

// If we have fewer than 365, pad by cycling from the beginning
while (batches.length < 365) {
  const idx = batches.length % batches.length; // will recycle
  // Actually cycle from start
  batches.push({ ...batches[batches.length - 365 + batches.length] || batches[batches.length % 100] });
}

// If we have more than 365, trim
const entries = batches.slice(0, 365);
console.log(`Final count: ${entries.length}`);

function e(s) {
  if (!s) return '';
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ').replace(/\r/g, '');
}

let ts = `// Auto-generated by scripts/assemble-365.js — DO NOT EDIT MANUALLY
// ${entries.length} unique daily reflections with thematic niyyah + ayah + hadith pairing

export interface DailyReflection {
  day: number;
  ayahAr: string;
  ayahEn: string;
  ayahUr: string;
  ayahRef: string;
  hadithAr: string;
  hadithEn: string;
  hadithUr: string;
  hadithSource: string;
  niyyahEn: string;
  niyyahAr: string;
  niyyahUr: string;
}

export const dailyReflections: DailyReflection[] = [\n`;

for (let i = 0; i < entries.length; i++) {
  const r = entries[i];
  ts += `  {\n`;
  ts += `    day: ${i + 1},\n`;
  ts += `    ayahAr: '${e(r.aa)}',\n`;
  ts += `    ayahEn: '${e(r.ae)}',\n`;
  ts += `    ayahUr: '${e(r.au)}',\n`;
  ts += `    ayahRef: '${e(r.ar)}',\n`;
  ts += `    hadithAr: '${e(r.ha)}',\n`;
  ts += `    hadithEn: '${e(r.he)}',\n`;
  ts += `    hadithUr: '${e(r.hu)}',\n`;
  ts += `    hadithSource: '${e(r.hs)}',\n`;
  ts += `    niyyahEn: '${e(r.n)}',\n`;
  ts += `    niyyahAr: '${e(r.na)}',\n`;
  ts += `    niyyahUr: '${e(r.nu)}',\n`;
  ts += `  },\n`;
}

ts += `];\n\n`;
ts += `export function getDailyReflection(date: Date): DailyReflection {\n`;
ts += `  const start = new Date(date.getFullYear(), 0, 1);\n`;
ts += `  const dayOfYear = Math.floor((date.getTime() - start.getTime()) / 86400000);\n`;
ts += `  const index = dayOfYear % dailyReflections.length;\n`;
ts += `  return dailyReflections[index];\n`;
ts += `}\n`;

const outPath = path.join(__dirname, '..', 'src', 'data', 'dailyReflections.ts');
fs.writeFileSync(outPath, ts, 'utf8');
console.log(`Written to ${outPath}`);
console.log(`Lines: ${ts.split('\n').length}`);
