const fs = require('fs');
const path = require('path');

function esc(s) { return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'"); }

// [theme, niyyahEn, niyyahAr, niyyahUr]
const NIYYAHS = [
// SABR (1-16)
['sabr','Today, I intend to respond to every difficulty with patience, trusting that Allah\'s wisdom is behind every test.','نيتي اليوم أن أواجه كل صعوبة بالصبر، واثقاً بأن حكمة الله وراء كل ابتلاء.','آج میری نیت ہے کہ ہر مشکل کا صبر سے سامنا کروں، اللہ کی حکمت پر بھروسہ رکھتے ہوئے۔'],
['sabr','Today, I intend to accept whatever outcome comes without complaint, knowing it is from Allah\'s decree.','نيتي اليوم أن أتقبل كل ما يأتيني دون شكوى، عالماً أنه من قدر الله.','آج میری نیت ہے کہ جو بھی نتیجہ آئے بغیر شکایت قبول کروں۔'],
['sabr','Today, I intend to say Inna lillahi wa inna ilayhi rajiun at every setback instead of complaining.','نيتي اليوم أن أقول إنا لله وإنا إليه راجعون عند كل مصيبة بدلاً من الشكوى.','آج میری نیت ہے کہ ہر مصیبت پر شکایت کی بجائے إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ کہوں۔'],
['sabr','Today, I intend to be patient with people who test my limits, seeking Allah\'s reward for self-restraint.','نيتي اليوم أن أصبر على من يختبر حدودي، طالباً أجر الله على ضبط النفس.','آج میری نیت ہے کہ ان لوگوں پر صبر کروں جو میری حدود آزماتے ہیں۔'],
['sabr','Today, I intend to wait for Allah\'s timing without rushing, knowing what is meant for me will never miss me.','نيتي اليوم أن أنتظر توقيت الله دون استعجال، عالماً أن ما قُدِّر لي لن يخطئني.','آج میری نیت ہے کہ اللہ کے وقت کا بغیر جلدبازی انتظار کروں۔'],
['sabr','Today, I intend to endure hardship silently, confiding only in Allah through prayer.','نيتي اليوم أن أتحمل المشقة بصمت، مناجياً الله وحده في صلاتي.','آج میری نیت ہے کہ تکلیف خاموشی سے برداشت کروں، صرف اللہ سے نماز میں فریاد کروں۔'],
['sabr','Today, I intend to see every delay as divine redirection, not denial.','نيتي اليوم أن أرى كل تأخير توجيهاً إلهياً لا حرماناً.','آج میری نیت ہے کہ ہر تاخیر کو اللہ کی طرف سے نئی سمت سمجھوں۔'],
['sabr','Today, I intend to persevere in my work without losing hope, remembering Allah rewards persistence.','نيتي اليوم أن أثابر في عملي دون يأس، متذكراً أن الله يجزي المثابرين.','آج میری نیت ہے کہ مایوس ہوئے بغیر اپنے کام میں لگا رہوں۔'],
['sabr','Today, I intend to bear physical discomfort with gratitude, remembering it expiates sins.','نيتي اليوم أن أتحمل الألم الجسدي بالشكر، متذكراً أنه يكفر الذنوب.','آج میری نیت ہے کہ جسمانی تکلیف کو شکر سے برداشت کروں۔'],
['sabr','Today, I intend to choose patience over revenge when wronged, forgiving for Allah\'s sake.','نيتي اليوم أن أختار الصبر على الانتقام إذا ظُلمت، مسامحاً لوجه الله.','آج میری نیت ہے کہ ظلم ہونے پر انتقام کی بجائے صبر اختیار کروں۔'],
['sabr','Today, I intend to remain calm in traffic, queues, and waiting, practicing sabr in small moments.','نيتي اليوم أن أبقى هادئاً في الزحام والطوابير والانتظار.','آج میری نیت ہے کہ ٹریفک اور قطاروں میں پرسکون رہوں۔'],
['sabr','Today, I intend to face my worries with dhikr rather than anxiety.','نيتي اليوم أن أواجه همومي بالذكر بدلاً من القلق.','آج میری نیت ہے کہ اپنی پریشانیوں کا سامنا ذکر سے کروں نہ کہ بے چینی سے۔'],
['sabr','Today, I intend to treat every trial as a hidden gift that purifies my soul.','نيتي اليوم أن أعامل كل ابتلاء كهدية خفية تزكي نفسي.','آج میری نیت ہے کہ ہر آزمائش کو روح کو پاک کرنے والا پوشیدہ تحفہ سمجھوں۔'],
['sabr','Today, I intend not to let any setback define my mood, anchoring my peace in Allah alone.','نيتي اليوم ألا أسمح لأي انتكاسة أن تحدد مزاجي.','آج میری نیت ہے کہ کسی ناکامی کو اپنے مزاج پر حاوی نہ ہونے دوں۔'],
['sabr','Today, I intend to fast from complaining entirely, replacing each complaint with Alhamdulillah.','نيتي اليوم أن أصوم عن الشكوى تماماً، مستبدلاً كل شكوى بالحمد لله.','آج میری نیت ہے کہ شکایت سے مکمل روزہ رکھوں، ہر شکایت کی جگہ الحمد للہ کہوں۔'],
['sabr','Today, I intend to comfort someone in pain with my presence and patience.','نيتي اليوم أن أواسي شخصاً يتألم بحضوري وصبري.','آج میری نیت ہے کہ کسی تکلیف میں مبتلا شخص کو اپنی موجودگی اور صبر سے تسلی دوں۔'],
// SHUKR (17-32)
['shukr','Today, I intend to begin my morning by naming five blessings I take for granted and thanking Allah for each.','نيتي اليوم أن أبدأ صباحي بذكر خمس نعم أعتبرها مسلّمات وأشكر الله عليها.','آج میری نیت ہے کہ صبح پانچ نعمتوں کا نام لے کر شروع کروں جو میں معمولی سمجھتا ہوں۔'],
['shukr','Today, I intend to thank at least three people who have helped me, in person or by message.','نيتي اليوم أن أشكر ثلاثة أشخاص ساعدوني على الأقل.','آج میری نیت ہے کہ کم از کم تین لوگوں کا شکریہ ادا کروں جنہوں نے میری مدد کی۔'],
['shukr','Today, I intend to notice the small blessings: clean water, a safe home, the ability to breathe.','نيتي اليوم أن ألاحظ النعم الصغيرة: الماء النظيف، البيت الآمن، القدرة على التنفس.','آج میری نیت ہے کہ چھوٹی نعمتوں پر غور کروں: صاف پانی، محفوظ گھر، سانس لینے کی صلاحیت۔'],
['shukr','Today, I intend to write down ten things I am grateful for and reflect on each one.','نيتي اليوم أن أكتب عشرة أشياء أنا ممتن لها وأتأمل في كل واحدة.','آج میری نیت ہے کہ دس چیزیں لکھوں جن کا میں شکرگزار ہوں اور ہر ایک پر غور کروں۔'],
['shukr','Today, I intend to express gratitude to my parents for the sacrifices they have made.','نيتي اليوم أن أعبر عن امتناني لوالديّ على تضحياتهما.','آج میری نیت ہے کہ والدین کی قربانیوں پر ان کا شکریہ ادا کروں۔'],
['shukr','Today, I intend to make sujud ash-shukr for a blessing I recently received.','نيتي اليوم أن أسجد سجدة الشكر على نعمة حصلت عليها مؤخراً.','آج میری نیت ہے کہ حال ہی میں ملی کسی نعمت پر سجدہ شکر ادا کروں۔'],
['shukr','Today, I intend to turn a moment of difficulty into an opportunity for shukr, finding the hidden blessing.','نيتي اليوم أن أحول لحظة صعوبة إلى فرصة للشكر، باحثاً عن النعمة الخفية.','آج میری نیت ہے کہ مشکل کے لمحے کو شکر کا موقع بناؤں، پوشیدہ نعمت ڈھونڈتے ہوئے۔'],
['shukr','Today, I intend to use each blessing I enjoy as motivation to serve others.','نيتي اليوم أن أستخدم كل نعمة أتمتع بها كدافع لخدمة الآخرين.','آج میری نیت ہے کہ ہر نعمت کو دوسروں کی خدمت کا محرک بناؤں۔'],
['shukr','Today, I intend to say Alhamdulillah after every meal, truly meaning it.','نيتي اليوم أن أقول الحمد لله بعد كل وجبة بصدق وإخلاص.','آج میری نیت ہے کہ ہر کھانے کے بعد دل سے الحمد للہ کہوں۔'],
['shukr','Today, I intend to look at what I have rather than what I lack, and feel contentment.','نيتي اليوم أن أنظر إلى ما أملك بدلاً مما ينقصني، وأشعر بالرضا.','آج میری نیت ہے کہ جو میرے پاس ہے اسے دیکھوں نہ کہ جو نہیں ہے، اور قناعت محسوس کروں۔'],
['shukr','Today, I intend to thank Allah for my health by using my body for something good.','نيتي اليوم أن أشكر الله على صحتي باستخدام جسدي في شيء نافع.','آج میری نیت ہے کہ اللہ کو اپنی صحت کا شکریہ اپنے جسم کو کسی اچھے کام میں لگا کر ادا کروں۔'],
['shukr','Today, I intend to share a blessing I have with someone who needs it.','نيتي اليوم أن أشارك نعمة أملكها مع شخص يحتاجها.','آج میری نیت ہے کہ اپنی کوئی نعمت کسی ضرورت مند کے ساتھ بانٹوں۔'],
['shukr','Today, I intend to replace envy with gratitude whenever I see someone with more than me.','نيتي اليوم أن أستبدل الحسد بالشكر كلما رأيت شخصاً لديه أكثر مني.','آج میری نیت ہے کہ جب بھی کسی کو اپنے سے زیادہ دیکھوں تو حسد کی جگہ شکر کروں۔'],
['shukr','Today, I intend to remember that every heartbeat is a gift and live this day with full awareness.','نيتي اليوم أن أتذكر أن كل نبضة قلب هدية وأعيش هذا اليوم بوعي كامل.','آج میری نیت ہے کہ یاد رکھوں ہر دل کی دھڑکن ایک تحفہ ہے اور مکمل آگاہی سے یہ دن گزاروں۔'],
['shukr','Today, I intend to find something to be grateful for in every single hour of this day.','نيتي اليوم أن أجد شيئاً أشكر الله عليه في كل ساعة من هذا اليوم.','آج میری نیت ہے کہ دن کے ہر گھنٹے میں شکر گزاری کی کوئی وجہ ڈھونڈوں۔'],
['shukr','Today, I intend to remember those who have less and feel deep gratitude for what Allah gave me.','نيتي اليوم أن أتذكر من لديهم أقل وأشعر بامتنان عميق لما أعطاني الله.','آج میری نیت ہے کہ ان لوگوں کو یاد کروں جن کے پاس کم ہے اور اللہ کی عطا پر گہرا شکر محسوس کروں۔'],
// TAWAKKUL (33-48)
['tawakkul','Today, I intend to place my trust in Allah regarding a matter that worries me, doing my part then leaving the outcome to Him.','نيتي اليوم أن أتوكل على الله في أمر يقلقني، فاعلاً ما بوسعي تاركاً النتيجة له.','آج میری نیت ہے کہ ایک پریشان کن معاملے میں اللہ پر بھروسہ کروں، اپنا حصہ کر کے نتیجہ اللہ پر چھوڑ دوں۔'],
['tawakkul','Today, I intend to tie my camel and trust Allah, preparing well while relying on His plan.','نيتي اليوم أن أعقل ناقتي وأتوكل على الله، محسناً الإعداد مع الاعتماد على تدبيره.','آج میری نیت ہے کہ اپنا اونٹ باندھوں اور اللہ پر بھروسہ کروں، اچھی تیاری کے ساتھ اس کی تدبیر پر اعتماد رکھوں۔'],
['tawakkul','Today, I intend to stop overthinking about the future and trust that Allah has a better plan.','نيتي اليوم أن أتوقف عن التفكير المفرط بالمستقبل وأثق بأن الله لديه خطة أفضل.','آج میری نیت ہے کہ مستقبل کے بارے میں زیادہ سوچنا چھوڑ دوں اور یقین رکھوں کہ اللہ کا منصوبہ بہتر ہے۔'],
['tawakkul','Today, I intend to say HasbiyAllahu wa nimal wakeel when anxiety creeps in.','نيتي اليوم أن أقول حسبي الله ونعم الوكيل عندما يتسلل القلق إلي.','آج میری نیت ہے کہ جب بے چینی محسوس ہو تو حسبی اللہ ونعم الوکیل کہوں۔'],
['tawakkul','Today, I intend to release my grip on controlling everything and surrender outcomes to Allah.','نيتي اليوم أن أتخلى عن محاولة التحكم بكل شيء وأسلم النتائج لله.','آج میری نیت ہے کہ ہر چیز پر قابو پانے کی کوشش چھوڑ دوں اور نتائج اللہ کو سونپ دوں۔'],
['tawakkul','Today, I intend to make istikhara before a decision and trust whatever Allah facilitates.','نيتي اليوم أن أصلي الاستخارة قبل قرار وأثق بما ييسره الله.','آج میری نیت ہے کہ کسی فیصلے سے پہلے استخارہ کروں اور جو اللہ آسان کرے اس پر بھروسہ کروں۔'],
['tawakkul','Today, I intend to remember that my rizq is already written and not chase it with desperation.','نيتي اليوم أن أتذكر أن رزقي مكتوب ولا أسعى إليه بيأس.','آج میری نیت ہے کہ یاد رکھوں میرا رزق پہلے سے لکھا ہے اور مایوسی سے اس کے پیچھے نہ بھاگوں۔'],
['tawakkul','Today, I intend to look at the birds who go out hungry and return full, trusting the Provider.','نيتي اليوم أن أنظر للطيور التي تغدو خماصاً وتروح بطاناً، واثقاً بالرزاق.','آج میری نیت ہے کہ پرندوں کو دیکھوں جو خالی پیٹ نکلتے ہیں اور بھرے واپس آتے ہیں، رزاق پر بھروسہ رکھتے ہوئے۔'],
['tawakkul','Today, I intend to trust Allah\'s timing for answered prayers, knowing He responds at the perfect moment.','نيتي اليوم أن أثق بتوقيت الله في إجابة الدعاء، عالماً أنه يستجيب في اللحظة المثالية.','آج میری نیت ہے کہ دعا کی قبولیت میں اللہ کے وقت پر بھروسہ کروں۔'],
['tawakkul','Today, I intend to let go of a closed door and trust that Allah is opening a better one.','نيتي اليوم أن أتقبل باباً مغلقاً واثقاً بأن الله يفتح أفضل منه.','آج میری نیت ہے کہ بند دروازے کو قبول کروں اور یقین رکھوں کہ اللہ بہتر دروازہ کھول رہا ہے۔'],
['tawakkul','Today, I intend to start my day saying Bismillah tawakkaltu alAllah, surrendering my plans to Him.','نيتي اليوم أن أبدأ يومي بقول بسم الله توكلت على الله، مسلماً خططي له.','آج میری نیت ہے کہ دن کا آغاز بسم اللہ توکلت علی اللہ کہہ کر کروں، اپنے منصوبے اللہ کے سپرد کرتے ہوئے۔'],
['tawakkul','Today, I intend to replace worry about finances with trust in Ar-Razzaq, the Provider.','نيتي اليوم أن أستبدل القلق المادي بالثقة في الرزاق.','آج میری نیت ہے کہ مالی فکر کی جگہ الرزاق پر بھروسہ رکھوں۔'],
['tawakkul','Today, I intend to give something in charity even when I feel I don\'t have enough, trusting Allah to replenish.','نيتي اليوم أن أتصدق حتى وإن شعرت بأن ما لدي لا يكفي، واثقاً بأن الله سيعوضني.','آج میری نیت ہے کہ صدقہ دوں چاہے مجھے لگے کہ میرے پاس کافی نہیں، اللہ سے بھروسہ رکھتے ہوئے کہ وہ پورا کرے گا۔'],
['tawakkul','Today, I intend to sleep peacefully tonight, entrusting all my affairs to Allah before closing my eyes.','نيتي اليوم أن أنام بسلام الليلة، مفوضاً جميع أموري لله قبل إغماض عيني.','آج میری نیت ہے کہ آج رات سکون سے سوؤں، آنکھیں بند کرنے سے پہلے اپنے تمام معاملات اللہ کو سونپ دوں۔'],
['tawakkul','Today, I intend to trust that every person I meet and every event today is part of Allah\'s perfect arrangement.','نيتي اليوم أن أثق بأن كل شخص ألقاه وكل حدث هو جزء من تدبير الله الكامل.','آج میری نیت ہے کہ یقین رکھوں ہر شخص جس سے ملوں اور ہر واقعہ اللہ کی کامل تدبیر کا حصہ ہے۔'],
['tawakkul','Today, I intend to perform my best effort at work and leave promotion and success to Allah.','نيتي اليوم أن أبذل أفضل جهدي في عملي وأترك الترقية والنجاح لله.','آج میری نیت ہے کہ کام میں اپنی بہترین کوشش کروں اور ترقی اور کامیابی اللہ پر چھوڑ دوں۔'],
// TAWBAH (49-60)
['tawbah','Today, I intend to make sincere tawbah for a sin I have been repeating, resolving firmly not to return to it.','نيتي اليوم أن أتوب توبة نصوحاً من ذنب أكرره، عازماً ألا أعود إليه.','آج میری نیت ہے کہ ایک بار بار ہونے والے گناہ سے سچی توبہ کروں، پکا ارادہ کرتے ہوئے کہ واپس نہ لوٹوں۔'],
['tawbah','Today, I intend to seek Allah\'s forgiveness 100 times, reflecting on my shortcomings with humility.','نيتي اليوم أن أستغفر الله مائة مرة، متأملاً في تقصيري بتواضع.','آج میری نیت ہے کہ سو مرتبہ اللہ سے استغفار کروں، عاجزی سے اپنی کوتاہیوں پر غور کرتے ہوئے۔'],
['tawbah','Today, I intend to identify one bad habit and begin the process of leaving it for Allah\'s sake.','نيتي اليوم أن أحدد عادة سيئة وأبدأ تركها لوجه الله.','آج میری نیت ہے کہ ایک بری عادت پہچانوں اور اللہ کی خاطر اسے چھوڑنے کا آغاز کروں۔'],
['tawbah','Today, I intend to pray two rakat of tawbah, pouring my heart out to Allah in repentance.','نيتي اليوم أن أصلي ركعتي التوبة، سائلاً الله المغفرة بكل قلبي.','آج میری نیت ہے کہ دو رکعت توبہ کی نماز پڑھوں، اللہ سے دل کھول کر معافی مانگوں۔'],
['tawbah','Today, I intend to remember that Allah loves those who repent, and approach Him with hope not despair.','نيتي اليوم أن أتذكر أن الله يحب التوابين، وأقبل عليه بالرجاء لا اليأس.','آج میری نیت ہے کہ یاد رکھوں اللہ توبہ کرنے والوں سے محبت کرتا ہے، اور مایوسی نہیں امید سے اس کی طرف آؤں۔'],
['tawbah','Today, I intend to forgive myself for past mistakes as I seek Allah\'s forgiveness, and move forward.','نيتي اليوم أن أسامح نفسي على أخطائي الماضية كما أطلب مغفرة الله، وأمضي قُدماً.','آج میری نیت ہے کہ اپنی پچھلی غلطیوں پر خود کو معاف کروں جیسے اللہ سے معافی مانگتا ہوں، اور آگے بڑھوں۔'],
['tawbah','Today, I intend to make istighfar between prayers, turning each gap into an opportunity for renewal.','نيتي اليوم أن أستغفر بين الصلوات، محولاً كل فترة إلى فرصة للتجديد.','آج میری نیت ہے کہ نمازوں کے درمیان استغفار کروں، ہر وقفے کو تجدید کا موقع بناؤں۔'],
['tawbah','Today, I intend to delete or remove something from my life that leads me to sin.','نيتي اليوم أن أحذف أو أزيل شيئاً من حياتي يقودني إلى المعصية.','آج میری نیت ہے کہ اپنی زندگی سے کوئی ایسی چیز حذف کروں جو مجھے گناہ کی طرف لے جاتی ہے۔'],
['tawbah','Today, I intend to return something I owe, fix a wrong I committed, or apologize to someone I hurt.','نيتي اليوم أن أُعيد حقاً أدين به، أو أصلح خطأً ارتكبته، أو أعتذر لمن أسأت إليه.','آج میری نیت ہے کہ کوئی واجب الادا چیز واپس کروں، کوئی غلطی درست کروں، یا کسی سے معافی مانگوں جسے تکلیف دی۔'],
['tawbah','Today, I intend to close my eyes tonight having made peace with Allah, knowing He is Al-Ghaffar.','نيتي اليوم أن أغمض عيني الليلة وقد صالحت الله، عالماً أنه الغفار.','آج میری نیت ہے کہ آج رات آنکھیں بند کروں اللہ سے صلح کر کے، یہ جانتے ہوئے کہ وہ الغفار ہے۔'],
['tawbah','Today, I intend to repent not just with my tongue but by changing a behavior that displeases Allah.','نيتي اليوم أن أتوب ليس بلساني فقط بل بتغيير سلوك يغضب الله.','آج میری نیت ہے کہ صرف زبان سے نہیں بلکہ اللہ کو ناراض کرنے والے عمل کو بدل کر توبہ کروں۔'],
['tawbah','Today, I intend to recite Sayyid al-Istighfar in the morning and evening with full consciousness.','نيتي اليوم أن أقرأ سيد الاستغفار صباحاً ومساءً بوعي كامل.','آج میری نیت ہے کہ صبح و شام سید الاستغفار مکمل شعور کے ساتھ پڑھوں۔'],
// IKHLAS (61-72)
['ikhlas','Today, I intend to check my intention before every deed, ensuring it is purely for Allah\'s pleasure.','نيتي اليوم أن أراجع نيتي قبل كل عمل، متأكداً أنها خالصة لمرضاة الله.','آج میری نیت ہے کہ ہر عمل سے پہلے اپنی نیت جانچوں، یقینی بناتے ہوئے کہ یہ صرف اللہ کی رضا کے لیے ہے۔'],
['ikhlas','Today, I intend to do a good deed secretly that only Allah knows about.','نيتي اليوم أن أعمل عملاً صالحاً سراً لا يعلمه إلا الله.','آج میری نیت ہے کہ خفیہ طور پر ایک نیکی کروں جس کا صرف اللہ کو علم ہو۔'],
['ikhlas','Today, I intend to worship without seeking praise from anyone, dedicating every action to Allah.','نيتي اليوم أن أعبد الله دون طلب ثناء من أحد، مخلصاً كل فعل لله.','آج میری نیت ہے کہ کسی کی تعریف کے بغیر عبادت کروں، ہر عمل اللہ کے لیے خالص رکھوں۔'],
['ikhlas','Today, I intend to give charity without telling anyone, keeping it between me and Allah.','نيتي اليوم أن أتصدق دون إخبار أحد، جاعلاً ذلك بيني وبين الله.','آج میری نیت ہے کہ کسی کو بتائے بغیر صدقہ دوں، یہ معاملہ میرے اور اللہ کے درمیان رکھوں۔'],
['ikhlas','Today, I intend to help someone without expecting anything in return, not even thanks.','نيتي اليوم أن أساعد شخصاً دون انتظار أي مقابل، ولا حتى الشكر.','آج میری نیت ہے کہ بدلے میں کچھ بھی توقع کیے بغیر کسی کی مدد کروں، شکریہ بھی نہیں۔'],
['ikhlas','Today, I intend to resist the urge to post about my good deeds on social media.','نيتي اليوم أن أقاوم الرغبة في نشر أعمالي الصالحة على وسائل التواصل.','آج میری نیت ہے کہ سوشل میڈیا پر اپنی نیکیاں شیئر کرنے کی خواہش کا مقابلہ کروں۔'],
['ikhlas','Today, I intend to renew my intention in the middle of every act of worship.','نيتي اليوم أن أجدد نيتي في منتصف كل عبادة.','آج میری نیت ہے کہ ہر عبادت کے درمیان اپنی نیت تازہ کروں۔'],
['ikhlas','Today, I intend to serve my family with ihsan, not for obligation but genuinely for Allah.','نيتي اليوم أن أخدم أهلي بإحسان، لا لأنه واجب بل بإخلاص لله.','آج میری نیت ہے کہ اپنے خاندان کی خدمت احسان سے کروں، مجبوری سے نہیں بلکہ اللہ کے لیے خالص دل سے۔'],
['ikhlas','Today, I intend to perform salah as though I see Allah, knowing He sees me even if I don\'t see Him.','نيتي اليوم أن أصلي كأنني أرى الله، عالماً أنه يراني وإن لم أره.','آج میری نیت ہے کہ نماز ایسے پڑھوں جیسے اللہ کو دیکھ رہا ہوں، یہ جانتے ہوئے کہ وہ مجھے دیکھ رہا ہے۔'],
['ikhlas','Today, I intend to study and learn not for grades or status, but to benefit the Ummah for Allah\'s sake.','نيتي اليوم أن أتعلم لا من أجل الدرجات أو المكانة، بل لنفع الأمة ابتغاء وجه الله.','آج میری نیت ہے کہ علم حاصل کروں درجات یا مقام کے لیے نہیں بلکہ اللہ کی خاطر امت کو فائدہ پہنچانے کے لیے۔'],
['ikhlas','Today, I intend to examine whether I treat people differently based on their status, and correct that for Allah.','نيتي اليوم أن أتحقق هل أعامل الناس بشكل مختلف بحسب مكانتهم، وأصحح ذلك لله.','آج میری نیت ہے کہ جانچوں کیا میں لوگوں سے ان کے مقام کے حساب سے مختلف سلوک کرتا ہوں، اور اللہ کے لیے اسے درست کروں۔'],
['ikhlas','Today, I intend to fast my tongue from showing off about any knowledge or worship I possess.','نيتي اليوم أن أصوم لساني عن التباهي بأي علم أو عبادة أملكها.','آج میری نیت ہے کہ اپنی زبان کو کسی بھی علم یا عبادت پر فخر کرنے سے روکوں۔'],
];

console.log('Niyyahs defined:', NIYYAHS.length);
console.log('Themes covered so far:', [...new Set(NIYYAHS.map(n => n[0]))].join(', '));
fs.writeFileSync(path.join(__dirname, 'scripts', 'data', 'niyyahs-count.txt'), String(NIYYAHS.length));
