export interface DuaData {
  id: string;
  categoryId: string;
  textAr: string;
  translationEn: string;
  translationUr: string;
  transliteration: string;
  source: string;
  repetitions: number;
}

/**
 * Full Hisnul Muslim collection (Fortress of the Muslim).
 * Generated by scripts/build-duas.py — do not edit by hand.
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const duas: DuaData[] = require('../../assets/duas/hisnul-muslim.json');

export function countDuasInCategory(categoryId: string): number {
  return duas.filter((d) => d.categoryId === categoryId).length;
}

export function totalDuaCount(): number {
  return duas.length;
}
